# Generated by Django 3.2.23 on 2023-12-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnitsMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=255)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics_monitor.ministries')),
                ('unit_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics_monitor.unitsmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics_monitor.indicators')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics_monitor.territories')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddIndex(
            model_name='demographicstatistics',
            index=models.Index(fields=['-year'], name='demographic_year_77df01_idx'),
        ),
    ]
